module.exports = {
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e0c0af',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#a78b7c',
        'outline-variant': '#584235',
        'surface-tint': '#ffb68b',
        primary: '#ffb68b',
        'on-primary': '#522300',
        'primary-container': '#ff7a00',
        'on-primary-container': '#5c2800',
        'inverse-primary': '#994700',
        secondary: '#ffb955',
        'on-secondary': '#452b00',
        'secondary-container': '#dc9100',
        'on-secondary-container': '#4f3100',
        tertiary: '#ffb4a8',
        'on-tertiary': '#690000',
        'tertiary-container': '#ff7663',
        'on-tertiary-container': '#750000',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdbc8',
        'primary-fixed-dim': '#ffb68b',
        'on-primary-fixed': '#321200',
        'on-primary-fixed-variant': '#753400',
        'secondary-fixed': '#ffddb4',
        'secondary-fixed-dim': '#ffb955',
        'on-secondary-fixed': '#291800',
        'on-secondary-fixed-variant': '#633f00',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a8',
        'on-tertiary-fixed': '#410000',
        'on-tertiary-fixed-variant': '#920703',
        'surface-variant': '#353534',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.75rem', // 28px for cards and containers
        '3xl': '2.5rem', // 40px top-corner radius for bottom sheets
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'gutter-sm': '16px',
        'gutter-md': '24px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['Sora', 'sans-serif'],
        body: ['Montserrat', 'sans-serif'],
      },
    },
  },
};
